### PR TITLE
Save/Resume a transfer to the database

### PR DESCRIPTION
**Pull request by whikloj**
This is a partial solution to #76. 

What I am missing is the best way to handle resuming a transfer and then re-saving that transfer. Currently if you save 2 transfers, you can resume 1 but you can't save it again. So I need to tell that I am in a resumed transfer and update that one instead of creating a new one.

I think I can use the `?resume_transfer=<int>` in the GET of the URL, but I also was not sure if that was a good idea. So I am stopping here to get your review and input.

### CODE REVIEW

**Comment by whikloj** [comment]
Ok, I rebased this and added in checking for the `resume_id` when saving. So it will update the already saved transfer. Some little QOL changes that could be done but maybe could wait for the time-being?
1. **Save Form** button disappears when you already have the maximum number of saved transfers, could just be disabled.
2. The current form data is not saved, would probably need to run the `get_cleaned_data` but without form validation and then serialize it with the existing form data.
3. The deleting of a transfer has no confirmation page, probably a good idea in the long run.

**Review by danloveg — CHANGES_REQUESTED** [review]
Everything looks great, but could you add MAX_SAVED_TRANSFER_COUNT to the table of contents at the top of the `settings.rst` file? I think this would fall under Application Features.

**Review by danloveg — CHANGES_REQUESTED** [review]
Also, can you add validations for the new settings in the `recordtransfer/apps.py` file? I assume any number from zero to infinity could be used, and negative numbers should not be allowed.

If someone sets the value to zero, would this disable saving transfers? Can this be clarified in the `settings.rst` file?

**Review by danloveg — APPROVED** [review]
Great!

**Pull request merged**
