### PR TITLE
Fix minified assets being generated in development

### PR DESCRIPTION
**Pull request by yenaing-oo**
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/245

### CODE REVIEW

**Comment by yenaing-oo** [comment]
Strangely, after these changes, the static assets are no longer being minified in production:
image
It looks like the pipeline is being used, since the asset names have the numbers at the back.

Development works perfectly fine though.

**Comment by danloveg** [comment]
I wonder if explicitly setting `PIPELINE_ENABLED: USE_PIPELINE` would make a difference in the dictionary that configures django-pipeline:

https://django-pipeline.readthedocs.io/en/latest/configuration.html

**Comment by yenaing-oo** [comment]
> I wonder if explicitly setting `PIPELINE_ENABLED: USE_PIPELINE` would make a difference in the dictionary that configures django-pipeline:
> 
> https://django-pipeline.readthedocs.io/en/latest/configuration.html

Unfortunately not. Downgrading to Django ^3.0.0 did not do the trick either.

**Comment by danloveg** [comment]
Alright I think I'm going to call it here - we're spending way too much time wrestling with this django-pipeline tool. Let's work to migrate to some other JavaScript/TypeScript tool that's more suitable and customizable for doing the bundling/minification.

I'll open a new issue for migrating away from django-pipeline.

**Pull request closed without merging**
